### ISSUE TITLE
家具取得APIの修正

### ISSUE THREAD

**Issue by ShimadaTakutoLuke** [naka-c1024/Pasha-niture#96]
## 内容
以下の二つのAPIが動作しない？（おま環の可能性あり）
- GET /furniture
- GET /furniture/{furniture_id}

## 対処法
user_idの送信をリクエストボディではなくクエリパラメータの方がよさそう？

### 参考画像等
![image](https://github.com/naka-c1024/Pasha-niture/assets/68723774/7c7f6f6f-3701-444a-81f4-fbb29d3cac3e)
- https://github.com/tiangolo/fastapi/discussions/6450

**Comment by naka-c1024** [comment]
見つけていただきありがとうございます！
私の環境でもなりました(curlで全部実行してたので気づきませんでした...)
`user_id`をURLに見せるのはセキュリティ上よくないと思いつつ、とはいえhash化を今からするのは少し大変なのでそのままクエリパラメータにしちゃいます！

**Comment by ShimadaTakutoLuke** [comment]
了解です！
たしかにuser_idがパスに含まれるのは良くないって話もしてましたね！

**Comment by naka-c1024** [comment]
このままこのissue使って修正するのでReOpenしちゃいます！

**Comment by naka-c1024** [comment]
@ibuibukiki 
furnitureエンドポイントのGETメソッドに関しては一旦実装後回しでお願いしますmm
